[package]
name = "delta"
version = "0.0.8"
authors = ["Dan Davison <dandavison7@gmail.com>"]
edition = "2018"

[dependencies]
aho-corasick = "0.7.6"
ansi_term = "0.11.0"
atty = "0.2.13"
autocfg = "0.1.5"
base64 = "0.10.1"
bincode = "1.1.4"
bitflags = "1.1.0"
box_drawing = "0.1.2"
byteorder = "1.3.2"
cc = "1.0.38"
cfg-if = "0.1.9"
clap = "2.33.0"
clicolors-control = "1.0.0"
console = "0.7.7"
crc32fast = "1.2.0"
either = "1.5.2"
flate2 = "1.0.9"
fnv = "1.0.6"
heck = "0.3.1"
humantime = "1.2.0"
itertools = "0.8.0"
itoa = "0.4.4"
lazycell = "1.2.1"
lazy_static = "1.3.0"
libc = "0.2.60"
line-wrap = "0.1.1"
linked-hash-map = "0.5.2"
lock_api = "0.3.1"
memchr = "2.2.1"
miniz-sys = "0.1.12"
onig = "4.3.2"
onig_sys = "69.1.0"
parking_lot = "0.9.0"
parking_lot_core = "0.6.2"
pkg-config = "0.3.15"
plist = "0.4.2"
proc-macro2 = "0.4.30"
quick-error = "1.2.2"
quote = "0.6.13"
regex = "1.2.1"
regex-syntax = "0.6.11"
rustc_version = "0.2.3"
ryu = "1.0.0"
safemem = "0.3.1"
same-file = "1.0.5"
scopeguard = "1.0.0"
semver = "0.9.0"
semver-parser = "0.7.0"
serde = "1.0.98"
serde_derive = "1.0.98"
serde_json = "1.0.40"
shell-words = "0.1.0"
smallvec = "0.6.10"
strsim = "0.8.0"
structopt = "0.2.18"
structopt-derive = "0.2.18"
syntect = "3.2.0"
syn = "0.15.42"
termios = "0.3.1"
textwrap = "0.11.0"
thread_local = "0.3.6"
ucd-util = "0.1.5"
unicode-segmentation = "1.3.0"
unicode-width = "0.1.5"
unicode-xid = "0.1.0"
utf8-ranges = "1.0.4"
vec_map = "0.8.1"
version_check = "0.1.5"
walkdir = "2.2.9"
xml-rs = "0.8.0"
yaml-rust = "0.4.3"

[dependencies.error-chain]
version = "0.12.1"
default-features = false
features = []
